### PR TITLE
Upgrade to ELK 5.5.1

### PR DESCRIPTION
**Pull request by davidkarlsen**

### CODE REVIEW

**Comment by jlruizmlg** [comment]
Hi @davidkarlsen thanks for your contribution, but we need to modify another file in order to install the correct wazuhapp version.

https://github.com/wazuh/wazuh-docker/blob/master/kibana/config/wait-for-it.sh#L8

Do you like to change this parameter? or should i change after merge your pull request.

**Comment by davidkarlsen** [comment]
I've updated my PR with the additional fix - thanks!

**Comment by jlruizmlg** [comment]
Hi @davidkarlsen looks perfect! thanks, i go to create a new branch with this version to test and move to hub.docker.com.

**Comment by jlruizmlg** [comment]
Hi @davidkarlsen works perfect, hub.docker.com is creating the new images, thanks!!

**Pull request merged**
