### PR TITLE
Add DASHBOARD_USERNAME and DASHBOARD_PASSWORD environment variables

### PR DESCRIPTION
**Pull request by Scronkfinkle**
Resolves https://github.com/wazuh/wazuh-docker/issues/823

### CODE REVIEW

**Comment by vcerenu** [comment]
Hi @Scronkfinkle 
Thanks for your contribution!!
Can you apply your commits to the [4.4](https://github.com/wazuh/wazuh-docker/tree/4.4) branch? that is our current branch for 4.4.x version releases.

**Comment by Scronkfinkle** [comment]
@vcerenu Sure

**Comment by vcerenu** [comment]
In order to execute the PR checks correctly, it is necessary to build a new PR, could you build it again with the 4.4 base branch?

**Comment by Scronkfinkle** [comment]
New PR filed: https://github.com/wazuh/wazuh-docker/pull/827

**Pull request closed without merging**
