### PR TITLE
Support ARM

### PR DESCRIPTION
**Pull request by jeankhawand**
- add docker/metadata-action@v4 and docker/build-push-action@v4 to setup cross platform images
- only push images to registry when git event is push
#### Dependencies
- [x] map S6 overlay to right arch provided in platform matrix (⚠️  s6 support different archs)
- [x] use `TARGETARCH` to detect arch type on build
- [x] fetch manager deb based on `TARGETARCH` instead of relying on apt source
- [x] fetch filebeat same as manager (⚠️ only support arm64, amd64)
- [x] fetch goss same as manager (⚠️  goss support different archs)

### Indexer (WIP)

- [ ]  ⚠️ `export BASE_FILE=wazuh-indexer-base-${VERSION}-linux-x64.tar.xz` I was unable to find archive for arm. any plan for other arch support?

### Dashboard (WIP)

- [ ] ⚠️ `curl -o wazuh-dashboard-base.tar.xz https://${REPOSITORY}/stack/dashboard/wazuh-dashboard-base-${WAZUH_VERSION}-${WAZUH_TAG_REVISION}-linux-x64.tar.xz` I was unable to find archive for arm. any plan for other arch support?

### CODE REVIEW

**Comment by jeankhawand** [comment]
I was wondering if I should point it to 4.5.0 branch or keep it for master? just for the sake of testing I had to point versions to 4.5 since it is current and all required dependencies are accessible

**Review by tkbstudios — APPROVED** [review]
Everything seems fine shouldn't give issues when building

**Comment by tkbstudios** [comment]
Why the close?

**Comment by archef2000** [comment]
Why the close?
@jeankhawand
Would like to see this being merged?

**Pull request closed without merging**
