### PR TITLE
Explain environment variables

### LINKED ISSUE #160: Complete documentation: Describe each environment variable
Hello folks,

I think it'd be great if every `ENV VAR` used in the images would  be explained in the `README.md`, and also it can be included in the `Wazuh official documentation` once they're ready.
 
Feel free to share your thoughts on this here.

Regards

### PR DESCRIPTION
**Pull request by tnyeanderson**
Just getting started.... Fixes #160

### CODE REVIEW

**Comment by jm404** [comment]
Hi @tnyeanderson, is this ready for review? If so please convert it to a PR and we'll be glad to check it.

Best regards,

Jose

**Comment by tnyeanderson** [comment]
@jm404 definitely not ready for review. I was hoping that opening a pull request would attract more knowledgeable people to take a look and fill in the gaps (of which there are many, I only know a few of the environment variables).

With some help from the community perhaps we could fill in those gaps? I have also not taken a look since the [potential change in environment variables](https://github.com/wazuh/wazuh-docker/issues/160#issuecomment-566540780), so this may be way out of date.

Feel free to close this or perhaps get some new eyes on it, as I just don't have the knowledge to complete this PR.

**Comment by xr09** [comment]
Hey guys! Actually I have #160 assigned so I'll use @tnyeanderson's work here as a base and work on another PR adding the docs. 

Again thank you @tnyeanderson getting this started!

**Comment by xr09** [comment]
Used this as a base to create https://github.com/wazuh/wazuh-docker/pull/322, it's a draft so far, I'll continue updating there.

Closing this one. Thanks @tnyeanderson!

**Pull request closed without merging**
