### PR TITLE
Create JinSakai.pl

### PR DESCRIPTION
**Pull request by nu11secur1ty**
Dear friends, I made a little Perl installer which will be easing the client to install the Wazuh Docker ENV
BR

### CODE REVIEW

**Comment by nu11secur1ty** [comment]
more: https://www.youtube.com/watch?v=kQLTQVrcW_8 =)

**Review by nu11secur1ty — COMMENTED** [review]
Update =)

**Review by nu11secur1ty — COMMENTED** [review]
Up, after debug, if someone is already installed the Wazuh Docker =)

**Comment by xr09** [comment]
Hi there @nu11secur1ty,  thanks a lot for this contribution but we can't accept this feature since this repo aims to be as neutral as possible regarding the Docker environment of the user. 

Although, you could always start your own docker-installer project.

**Comment by nu11secur1ty** [comment]
Ok 🙂

**Pull request closed without merging**
